#!/usr/bin/env bash

. tsk/env

main() {
  local OPTIONS=(
    -C "${ARDUINO_JAVA}/hardware/tools/avr/etc/avrdude.conf"
    -p "${ARDUINO_BUILD_MCU}"
    -c "${ARDUINO_UPLOAD_PROTOCOL}"
    -P "${ARDUINO_UPLOAD_PORT}"
    -b "${ARDUINO_UPLOAD_SPEED}"
    -D
    -q
    -U "flash:w:${SESAME_PATH}/bin/main.ino.hex:i"
    -V
  )

  # reset the Arduino
  stty -f "${ARDUINO_UPLOAD_PORT}" 1200

  # wait for it...
  while :; do
    sleep 0.5
    [ -c "${ARDUINO_UPLOAD_PORT}" ] && break
  done

  # ...upload!
  "${ARDUINO_JAVA}/hardware/tools/avr/bin/avrdude" "${OPTIONS[@]}"
}

main
