#!/usr/bin/env bash

. tsk/env

main() {
  local OPTIONS=(
    -C "${ARDUINO_JAVA}/hardware/tools/avr/etc/avrdude.conf"
    -p "${ARDUINO_BUILD_MCU}"
    -c "${ARDUINO_UPLOAD_PROTOCOL}"
    -P "${ARDUINO_UPLOAD_PORT}"
    -b "${ARDUINO_UPLOAD_SPEED}"
    -D
    -U "flash:w:${SESAME_PATH}/bin/main.ino.hex:i"
  )

  stty -f "${ARDUINO_UPLOAD_PORT}" 1200
  sleep 1
  "${ARDUINO_JAVA}/hardware/tools/avr/bin/avrdude" "${OPTIONS[@]}"
}

main
